USE honduras;

create table departamento
(
	id_departamento varchar(2) not null primary key,
	departamento varchar(100) not null
);


create table municipio
(
	id_municipio varchar(4) not null primary key,
	municipio varchar(100) not null,
	id_departamento varchar(2) not null,
	constraint municipio_ibfk_1 foreign key (id_departamento) references departamento (id_departamento)
);


INSERT INTO departamento(departamento, id_departamento) VALUES ('Atlántida', '01');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Colón', '02');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Comayagua', '03');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Copán', '04');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Cortés', '05');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Choluteca', '06');
INSERT INTO departamento(departamento, id_departamento) VALUES ('El Paraíso', '07');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Francisco Morazán', '08');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Gracias a Dios', '09');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Intibucá', '10');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Islas de la Bahía', '11');
INSERT INTO departamento(departamento, id_departamento) VALUES ('La Paz', '12');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Lempira', '13');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Ocotepeque', '14');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Olancho', '15');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Santa Bárbara', '16');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Valle', '17');
INSERT INTO departamento(departamento, id_departamento) VALUES ('Yoro', '18');


INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('01','0101',' La Ceiba');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('01','0102',' El Porvenir');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('01','0103',' Esparta');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('01','0104',' Jutiapa');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('01','0105',' La Masica');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('01','0106',' San Francisco');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('01','0107',' Tela');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('01','0108',' Arizona');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('02','0201',' Trujillo');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('02','0202',' Balfate');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('02','0203',' Iriona');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('02','0204',' Limón');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('02','0205',' Sabá');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('02','0206',' Santa Fe');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('02','0207',' Sta. Rosa De Aguán');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('02','0208',' Sonaguera');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('02','0209',' Tocoa');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('02','0210',' Bonito Oriental');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0301',' Comayagua');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0302',' Ajuterique');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0303',' El Rosario');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0304',' Esquías');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0305',' Humuya');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0306',' La Libertad');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0307',' Lamaní');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0308',' La Trinidad');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0309',' Lejamaní');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0310',' Meámbar');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0311',' Minas De Oro');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0312',' Ojos De Agua');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0313',' San Jerónimo');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0314',' S. José De Comayag.');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0315',' S. José Del Potrero');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0316',' San Luis');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0317',' San Sebastián');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0318',' Siguatepeque');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0319',' Villa De S. Antonio');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0320',' Lajas');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('03','0321',' Taulabé');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0401',' Sta. Rosa De Copán');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0402',' Cabañas');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0403',' Concepción');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0404',' Copán Ruinas');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0405',' Corquín');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0406',' Cucuyagua');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0407',' Dolores');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0408',' Dulce Nombre');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0409',' El Paraíso');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0410',' Florida');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0411',' La Jigua');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0412',' La Unión');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0413',' Nueva Arcadia');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0414',' San Agustín');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0415',' San Antonio');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0416',' San Jerónimo');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0417',' San José');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0418',' San Juan De Opoa');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0419',' San Nicolás');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0420',' San Pedro');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0421',' Santa Rita');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0422',' Trinidad');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('04','0423',' Veracruz');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('05','0501',' San Pedro Sula');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('05','0502',' Choloma');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('05','0503',' Omoa');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('05','0504',' Pimienta');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('05','0505',' Potrerillos');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('05','0506',' Puerto Cortés');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('05','0507',' S. Antonio De Cortés');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('05','0508',' San Fco. De Yojoa');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('05','0509',' San Manuel');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('05','0510',' Sta. Cruz De Yojoa');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('05','0511',' Villanueva');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('05','0512',' La Lima');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0601',' Choluteca');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0602',' Apacilagua');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0603',' Concepción De María');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0604',' Duyure');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0606',' El Triunfo');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0607',' Marcovia');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0608',' Morolica');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0609',' Namasigüe');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0610',' Orocuina');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0611',' Pespire');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0612',' S. Antonio De Flores');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0613',' San Isidro');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0614',' San José');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0615',' S. Marcos De Colón');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('06','0616',' Sta. Ana De Yusguare');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0701',' Yuscarán');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0702',' Alauca');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0703',' Danlí');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0704',' El Paraíso');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0705',' Güinope');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0706',' Jacaleapa');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0707',' Liure');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0708',' Morocelí');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0709',' Oropolí');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0710',' Potrerillos');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0711',' S. Antonio De Flores');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0712',' San Lucas');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0713',' San Matías');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0714',' Soledad');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0715',' Teupasenti');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0716',' Texiguat');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0717',' Vado Ancho');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0718',' Yauyupe');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('07','0719',' Trojes');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0801',' Distrito Central');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0802',' Alubarén');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0803',' Cedros');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0804',' Curarén');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0805',' El Provenir');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0806',' Guaimaca');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0807',' La Libertad');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0808',' La Venta');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0809',' Lepaterique');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0811',' Marale');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0812',' Nueva Aremnia');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0813',' Ojojona');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0814',' Orica');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0815',' Reitoca');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0816',' Sabanagrande');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0817',' S. Antonio De Oriente');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0818',' San Buenaventura');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0819',' San Ignacio');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0820',' San Juan De Flores');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0821',' San Miguelito');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0822',' Santa Ana');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0823',' Santa Lucía');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0824',' Talanga');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0825',' Tatumbla');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0826',' Valle De Ángeles');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0827',' Villa De San Francisco');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('08','0828',' Vallecillo');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('09','0901',' Puerto Lempira');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('09','0902',' Brus Laguna');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('09','0903',' Ahuas');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('09','0904',' Juan Francisco Bulnes');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('09','0905',' Villeda Morales');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('09','0906',' Wampusirpe');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1001',' La Esperanza');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1002',' Camasca');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1003',' Colomoncagua');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1004',' Concepción');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1005',' Dolores');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1006',' Intibucá');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1007',' Jesú S De Otoro');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1008',' Magdalena');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1009',' Masaguara');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1010',' San Antonio');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1011',' San Isidro');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1012',' San Juan De Flores');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1013',' S. Marcos De La Sierra');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1014',' S. Miguel Guancapla');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1015',' Santa Lucía');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('10','1017',' S. Francisco Opalaca');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('11','1101',' Roatán');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('11','1102',' Guanaja');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('11','1103',' J. Santos Guardiola');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('11','1104',' Utila');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1201',' La Paz');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1202',' Aguanqueterique');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1203',' Cabañas');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1204',' Cane');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1205',' Chinacla');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1206',' Guajiquiro');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1207',' Lauterique');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1208',' Marcala');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1209',' Mercedes De Oriente');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1210',' Opatoro');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1211',' S. Antonio Del Norte');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1212',' San José');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1213',' San Juan');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1214',' San Pedro De Tutule');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1215',' Santa Ana');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1216',' Santa Elena');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1217',' Santa María');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1218',' Santiago Puringla');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('12','1219',' Yarula');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1301',' Gracias');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1302',' Belén');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1303',' Candelaria');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1304',' Cololaca');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1305',' Erandique');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1306',' Gualcinse');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1307',' Guarita');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1308',' La Campa');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1309',' La Iguala');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1310',' Las Flores');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1311',' La Unión');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1312',' La Virtud');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1313',' Lepaera');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1314',' Mapulaca');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1316',' San Andrés');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1317',' San Francisco');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1318',' San Juan Guarita');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1319',' San Manuel Colohete');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1320',' San Rafael');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1321',' San Sebastián');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1322',' Santa Cruz');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1323',' Talgua');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1324',' Tambla');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1325',' Tomala');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1326',' Valladolid');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1327',' Virginia');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('13','1328',' S. Marcos De Caiquín');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1401',' Nueva Ocotepeque');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1402',' Belén Gualcho');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1403',' Concepción');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1404',' Dolores Merendón');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1405',' Fraternidad');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1406',' La Encarnación');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1407',' La Labor');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1408',' Lucerna');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1409',' Mercedes');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1410',' San Fernando');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1411',' S. Francisco Del Valle');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1412',' San Jorge');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1413',' San Marcos');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1414',' Santa Fe');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1415',' Sensenti');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('14','1416',' Sinuapa');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1501',' Juticalpa');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1502',' Campamento');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1503',' Catacamas');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1504',' Concordia');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1505',' Dulce Nombre De Culmí');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1506',' El Rosario');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1507',' Esquipulas Del Norte');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1508',' Gualaco');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1509',' Guarizama');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1510',' Guata');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1512',' Jano');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1513',' La Unión');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1514',' Mangulile');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1515',' Manto');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1516',' Salamá');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1517',' San Esteban');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1518',' S. Francisco De Becerra');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1519',' S. Francisco De La Paz');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1520',' Santa María Del Real');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1521',' Silca');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1522',' Yocón');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('15','1523',' Froylan Turcios');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1601',' Santa Bárbara');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1602',' Arada');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1603',' Atima');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1604',' Azacualpa');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1605',' Ceguaca');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1606',' Colinas');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1607',' Concepción Del Norte');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1608',' Conceppción Del Sur');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1609',' Chinda');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1610',' El Níspero');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1611',' Gualala');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1612',' Ilama');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1613',' Macuelizo');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1614',' Naranjito');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1615',' Nueva Celilac');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1616',' Petoa');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1617',' Protección');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1618',' Quimistán');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1619',' S. Francisco De Ojuera');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1620',' San Luis');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1621',' San Marcos');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1622',' San Nicolás');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1623',' San Pedro Zacapa');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1624',' Santa Rita');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1625',' S. Vicente Centenario');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1626',' Trinidad');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1627',' Las Vegas');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('16','1628',' Nueva Frontera');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('17','1701',' Nacaome');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('17','1702',' Alianza');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('17','1703',' Amapala');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('17','1704',' Aramecina');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('17','1705',' Caridad');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('17','1706',' Goascorán');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('17','1707',' Langue');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('17','1708',' San Fco. De Coray');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('17','1709',' San Lorenzo');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('18','1801',' Yoro');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('18','1802',' Arenal');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('18','1803',' El Negrita');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('18','1804',' El Progreso');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('18','1805',' Jocón');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('18','1806',' Morazán');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('18','1807',' Olanchito');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('18','1808',' Santa Rita');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('18','1809',' Sulaco');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('18','1810',' Victoria');
INSERT INTO municipio (id_departamento, id_municipio, municipio) VALUES ('18','1811',' Yorito');